### ISSUE TITLE
Logical OR Example

### ISSUE THREAD

**Issue by pasetti** [ttsiodras/condition-decision-mcdc#1]
I am not sure that the argument presented here that gcov can achieve MC/DC coverage is correct. Consider the following condition:

   ` if (A || B) ....`

And now consider three test cases which exercise the following combinations:

```
(1)    A = True, B = True
(2)    A = False, B = True
(3)    A = False, B = False
```

These tests will give you:

-    Decision coverage (because test (1) makes the if-clause True and test (2) makes it False)
-    Condition coverage (because they cover all possible outcomes of A and B)

But I do not think that they will give you MC/DC because we do not have a situation where A alone determines a "True" outcome for the if-clause (for that purpose we would need a test case with A=True and B=False). And, yet, gcov will give you the following coverage:

```
        3:    5:    if (A || B)
branch  0 taken 2 (fallthrough)
branch  1 taken 1
branch  2 taken 1 (fallthrough)
branch  3 taken 1
```

Please let me know if you think that I made a mistake or overlooked something.

**Comment by ttsiodras** [comment]
Hi Alessandro - nice to see you again!

To the topic:  since this decision is a logical OR between two conditions, all C compilers will emit code that short-circuits the evaluation after the first condition if it is TRUE _(in your example, if "A" is True)_.  By definition, that means that the requirement from MC/DC ( _Each condition in a decision is shown to independently affect the outcome of the decision_ ) is automatically enforced for "A":  a TRUE value short-circuits, a FALSE value allows the rest of the conditions to impact the result.

SQLite makes [the same argument](https://www.sqlite.org/testing.html#branch_coverage_versus_mc_dc), BTW.

P.S. Note that this "MC/DC brainstorming" did have some weak spots, that were in the end addressed by work we did with GTD under the supervision of Andreas Jung. If the email address I have from you during the days of CHEOPS is correct, I can send you the presentation Andoni Arregi did about it.

**Comment by pasetti** [comment]
Hello Thanassis, it is good to be in touch again!

The argument you make in favour of gcov for MC/DC is intriguing. I would personally be inclined to accept it but I can see that there is potential room for reasonable disagreement ... 

My e-mail address has not changed. I would certainly appreciate receiving the presentation. I am keen to support the use of free/open software tools wherever possible,
